name: Deploy Portfolio to GitHub Pages

on:
  workflow_dispatch:  # Add "Run workflow" button

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: . 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
